---

- name: create ntp config for all nodes
  template:
    src: client_ntp.conf.j2
    dest: /etc/ntp.conf

- name: create ntp config for master node
  template:
    src: master_ntp.conf.j2
    dest: /etc/ntp.conf
  delegate_to: "{{ groups['ntp-master-node'][0] }}"

- name: restart ntpd
  systemd:
    name: ntpd
    state: restarted
