---

- name: change firewalll to enable port 2379
  command: "firewall-cmd --zone=public --add-port=2379/tcp --permanent"

- name: change firewalll to enable port 2380
  command: "firewall-cmd --zone=public --add-port=2380/tcp --permanent"

- name: change firewalll to enable port 4001
  command: "firewall-cmd --zone=public --add-port=4001/tcp --permanent"

- name: change firewalll to enable ntp service port
  command: "firewall-cmd --add-service=ntp --permanent"


- name: reload firewall to take effect
  command: "firewall-cmd --reload"
