---

- name: add l2packet pass firewall setting in system config
  template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: update k8s.conf sysctl file and exec
  sysctl: 
    name: "{{ item }}"
    value: 1
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
