---

- name: eanble l2packet pass firewall
  template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: sysctl k8s.conf
  sysctl: 
    name: "{{ item }}"
    value: 1
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
