---

- hosts: cluster
  become: yes
  roles:
    - role: system-prep
  tags:
    - system-prep

- hosts: cluster
  become: yes
  roles:
    - role: kube
  environment:
#    http_proxy: http://10.0.0.9:30080
#    https_proxy: http://10.0.0.9:30080
    http_proxy: http://192.168.20.221:30080
    https_proxy: http://192.168.20.221:30080
