---

- name: create etcd user and data dir
  import_tasks: create_etcd_user.yml
  
- name: download and install etcd bin
  import_tasks: install-etcd-bin.yml
  
- name: generate etcd certs
  import_tasks: gen-etcd-certs.yml
  
- name: generate etcd systemd and config
  import_tasks: gen-etcd-systemd.yml

- name: change ntp config to single time src and restart ntp
  import_tasks: change-ntp-config.yml

- name: change firewall config to enable port 2370 2380 ntp and reload rules
  import_tasks: change-firewall-config.yml
  
- name: start etcd
  import_tasks: etcd-start.yml
  
- name: restart etcd
  import_tasks: etcd-restart.yml
