---

- name: STARTING install ntp server ( change-ntp-config TASK)
  yum:
    name: ntp
    state: present

- name: STARTING change-ntp-config TASK. create ntp config for all nodes
  template:
    src: client_ntp.conf.j2
    dest: /etc/ntp.conf

- name: create specific ntp config for master ntp node
  template:
    src: master_ntp.conf.j2
    dest: /etc/ntp.conf
  run_once: true
  delegate_to: "{{ groups['ntp-master-node'][0] }}"

- name: restart ntpd of all node of cluster
  systemd:
    name: ntpd
    enabled: yes
    state: restarted
