---

#- hosts: cluster
#  vars:
#    etcd_client_port: 2379
#    etcd_ca_file: "/etc/etcd/ssl/etcd-ca.pem"
#    etcd_client_cert_file: "/etc/etcd/ssl/etcd-client.pem"
#    etcd_client_key_file: "/etc/etcd/ssl/etcd-client-key.pem"
#    etcd_bin_path: "/usr/local/bin"
#    flannel_network_config_key_json_file: "/etc/sysconfig/flannel-config-vxlan.json"
#    flannel_config_dir: "/etc/sysconfig"
#    flannel_network: "10.244.0.0/16"


# create flannel subnet config key on etcd

# tasks:

- name: copy flannel network config json file to the first etcd node
  template:
    src: flannel-config-vxlan.json.j2
    dest: "{{ flannel_network_config_key_json_file }}"
  delegate_to: "{{ groups['kube-masters'][0] }}"
  run_once: true


# copy make-master-ca-cert.sh to first master node
- name: copy write-flannel-etcd-keyvalue.sh
  copy:
    src: write-flannel-etcd-keyvalue.sh
    dest: "{{ flannel_config_dir }}"
    owner: root
    group: root
    mode: "0500"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"

# spawn to write-flannel-etcd-keyvalue.sh to write flannel network config key-value to etcd
- name: write flannel network config key-value to etcd on first node of kube-masters
  command:
    "{{ flannel_config_dir }}/write-flannel-etcd-keyvalue.sh"
  args:
#    creates: ""
    chdir: "{{ flannel_config_dir }}"
  environment:
    ETCD_CMD: "/usr/local/bin/etcdctl"
    ETCD_OPT: " --ca-file={{ etcd_ca_file }} --cert-file={{ etcd_client_cert_file }} --key-file={{ etcd_client_key_file }} --endpoints=https://{{ hostvars[groups['etcd-nodes'][0]]['host_ip_address'] }}:2379"
    ETCD_OP: " set"
    ETCD_TARGET: "/coreos.com/network/config"
    ETCD_SOURCE: "{{ flannel_network_config_key_json_file }}"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"
