---

- name: STARTING flannel-restart TASK.    restart flannel network service
  systemd:
    name: flannel
    daemon_reload: yes
    state: restarted
    enabled: yes
#  when: inventory_hostname in groups['kube-masters']

