---

#### generate kubernetes systemd service files for:
#    1. apiserver service
#    2. controller-manager service
#    3. scheduler service
#
  
- name: STARTING gen-kube-systemd TAKS. create kube apiserver systemd unit file
  template: 
    src: apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  when: inventory_hostname in groups['kube-masters']
  
- name: create kube controller-manager systemd unit file
  template:
    src: controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  when: inventory_hostname in groups['kube-masters']

- name: create kube scheduler systemd unit file
  template:
    src: scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
  when: inventory_hostname in groups['kube-masters']
    
