---

# file: roles/kube/tasks/gen-kube-config.yml
# generate kube config file (set cluster, credential, context, and default context)
# copy to ansible backup
# copy to kub home dire

# generate kube config file for every master node
- name: generate kub config - set cluster
#  command: >
#    "{{ kube_bin_dir }}"/kubectl config set-cluster kubernetes
#      --certificate-authority="{{ kube_ca_file }}" 
#      --embed-certs=true 
#      --server="{{ kube_apiserver_url }}"
#      --kubeconfig=admin.conf
  command: "/usr/local/bin/kubectl {{ arg_str_cluster }}"
  args:
    chdir: "{{ kube_conf_dir }}/"
  when: inventory_hostname in groups['kube-masters']

- name: generate kub config - set credential
#  command: >
#    "{{ kube_bin_dir }}"/kubectl config set-credentials kubernetes-admin 
#      --client-certificate="{{ kube_admin_cert_file }}"
#      --embed-certs=true 
#      --client-key="{{ kube_admin_key_file }}" 
#      --kubeconfig=admin.conf
  command: "/usr/local/bin/kubectl  {{ arg_str_credentials }}"
  args:
    chdir: "{{ kube_conf_dir }}/"
  when: inventory_hostname in groups['kube-masters']

- name: generate kub config - set context
#  command: >
#    "{{ kube_bin_dir }}"/kubectl config set-context kubernetes-admin@kubernetes
#      --cluster=kubernetes
#      --user=kubernetes-admin
#      --kubeconfig=admin.conf
  command: "/usr/local/bin/kubectl  {{ arg_str_context }}"
  args:
    chdir: "{{ kube_conf_dir }}/"
  when: inventory_hostname in groups['kube-masters']

- name: cp kub config to home
  command: cp /etc/kubernetes/admin.conf "{{ kube_home_dir }}/config"
#  args: 
  when: inventory_hostname in groups['kube-masters']

- name: generate kub config - set default context
#  command: >
#    "{{ kube_bin_dir }}"/kubectl config use-context kubernetes-admin@kubernetes 
#      --kubeconfig=admin.conf
  command: "/usr/local/bin/kubectl  {{ arg_str_defaultcontext }}"
  args:
    chdir: "{{ kube_conf_dir }}/"
  when: inventory_hostname in groups['kube-masters']

## copy kube config file admin.conf to ansible backup directory
#- name: fetch kube config file admin.conf to ansible backup directory
#  fetch:
#    src: "{{ kube_conf_dir }}/{{ item }}"
##    dest: "{{ ansible_tmp_kube_configs_dir }}/{{ hostvars[inventory_hostname] }}/{{ item }}"
#    dest: "{{ ansible_tmp_kube_configs_dir }}/{{ item }}"
#    flat: yes
#  with_items:
#    - admin.conf
#  when: inventory_hostname in groups['kube-masters']

## copy kube config file to kube home directory of every master node
#- name: copy kube config file to kube home directory of every master node
#  copy:
#    dest: "{{ kube_home_dir }}/config"
##    src:  "{{ ansible_tmp_kube_configs_dir }}/{{ hostvars[inventory_hostname] }}/admin.conf"
#    owner: "{{ kube_user }}"
#    group: "{{ kube_cert_group }}"
#  when: inventory_hostname in groups['kube-masters']
  
