---

- name: STARTING gen-etcd-systemd TAKS. create etcd systemd unit file
  template: 
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  when: inventory_hostname in groups['etcd-nodes']
  
    
- name: TASK gen-etcd-systemd - sub task create etcd ENV. create etcd env conf
  template: 
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: etcd
    group: etcd
    mode: 0540
  when: inventory_hostname in groups['etcd-nodes']    
