---

- name: STARTING kub-nodes-start TASK.    start kubernetes kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  when: inventory_hostname in groups['kube-nodes']

- name: start kubernetes kube-proxy service on kube-node
  systemd:
    name: kube-proxy
    daemon_reload: yes
    state: started
    enabled: yes
  when: inventory_hostname in groups['kube-nodes']

